### ISSUE TITLE
org.keycloak.models.KeycloakContext.getClient() is null

### ISSUE THREAD

**Issue by maxnasonov** [looorent/keycloak-configurable-token-api#13]
Hello,

I'm evaluating the provider on Keycloak version 25.0.5 (also tried 25.0.2) but after executing:

```
curl -X POST -d '{ "tokenLifespanInSeconds": 20}' -H "Content-Type: application/json" -H "Authorization: Bearer <ACCESS_TOKEN>" http://<KEYCLOAK_IP>/realms/test1/configurable-token
```

using access token returned by Keycloak:

```
{
  "accessToken": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIycnZ2LVBrZUlpbnZSVnMtZklxUjJWWWZQMEo4VDJiNFNqV05IV1pXZ0pvIn0.eyJleHAiOjE3MjY2MzgyNDUsImlhdCI6MTcyNjYzNzk0NSwianRpIjoiN2RmZGQ0MmYtYzAyNy00MTZlLThjOWMtMDkzYmY2NmQ4Yjc1IiwiaXNzIjoiaHR0cDovLzEwLjU2LjI1NS4xMjAvcmVhbG1zL3Rlc3QxIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjI2NjQyMWExLTEyNTAtNGUzOC1iZDY5LWE2ODViODg4ZjEyZSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3QxLWNsaWVudCIsInNpZCI6IjQwNjA1ZjNhLWYyMzItNGZmYi05OTZmLWI1N2M2ZTJhOWU3MiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXRlc3QxIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiVGVzdDFOb0xkYXAgTmFzb25vdiIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QxLXVzZXIiLCJnaXZlbl9uYW1lIjoiVGVzdDFOb0xkYXAiLCJmYW1pbHlfbmFtZSI6Ik5hc29ub3YiLCJlbWFpbCI6InRlc3QxQG5hc29ub3YubWUifQ.BVwH287CjyPsduSSgYqx0YqPzunOjoY4AWEkpO0fokisL2wwSwRKnSgI3olp2ZZjXTvaKi_lcx2_l37js_JE33Wvsd2isqqfGdufzeczR7Ga3HGM5qhGvyn1Y481jADa5-iz6n6QMGequEsKDV-abrI4TIIQE3z5BpxInWD3o_zh1vA8Lkwz3_p7aXYlki1xnmAOdBu0kjTyMJByi7mzU5zLGbuFM_oClodGJbI8M5WE3VwOckrqSeuyxVkpae4nqf8UvyhOjJoY6a1TQ57Ehooiz7tvRwPFtETj608SZcddloSmXd8LeUr0RkcthSZ8sW_zh43gY2ZmScI1V4Bcrw",
  "refreshToken": "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZjkzZjI3Yi1hNjdiLTRlNjgtOTg0Ny04YjgwZDhiYzhkNDEifQ.eyJleHAiOjE3MjY2Mzk3NDUsImlhdCI6MTcyNjYzNzk0NSwianRpIjoiYjMzZjBmMzMtOWRiNi00OTRhLTg1ZWEtNTFiN2ZlZDY5ZTI4IiwiaXNzIjoiaHR0cDovLzEwLjU2LjI1NS4xMjAvcmVhbG1zL3Rlc3QxIiwiYXVkIjoiaHR0cDovLzEwLjU2LjI1NS4xMjAvcmVhbG1zL3Rlc3QxIiwic3ViIjoiMjY2NDIxYTEtMTI1MC00ZTM4LWJkNjktYTY4NWI4ODhmMTJlIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InRlc3QxLWNsaWVudCIsInNpZCI6IjQwNjA1ZjNhLWYyMzItNGZmYi05OTZmLWI1N2M2ZTJhOWU3MiIsInNjb3BlIjoib3BlbmlkIGJhc2ljIGFjciByb2xlcyBlbWFpbCBwcm9maWxlIHdlYi1vcmlnaW5zIn0.ewNeY8fc6qN2XCANFvH7aUnuOuTdp4UtJh7WNPIwxkr0ey_gVRpgDkMLJygOL7RTJJbbXjD3yzoxib4ZE3eYEQ",
  "expiresIn": 300
}
```

I've got:

```
{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}
```

Server logs at that moment:
```
...
2024-09-18 05:39:10,973 WARN  [be.looorent.ConfigurableTokenResourceProviderFactory] (executor-thread-14) Keycloak-ConfigurableToken : Long lived role name provided, using default one.
2024-09-18 05:39:10,973 WARN  [be.looorent.ConfigurableTokenResourceProviderFactory] (executor-thread-14) Keycloak-ConfigurableToken : no cors origin is defined in environment variables. Using '[*]'.
2024-09-18 05:39:10,973 INFO  [be.looorent.ConfigurableTokenResourceProviderFactory] (executor-thread-14) Keycloak-ConfigurableToken is configured with: longLivedTokenRole=long_lived_token
2024-09-18 05:39:10,976 INFO  [be.looorent.ConfigurableTokenResource] (executor-thread-14) Configurable token requested for username=test1-user and client=test1-client on realm=test1
2024-09-18 05:39:10,977 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-14) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.ClientModel.getAttribute(String)" because the return value of "org.keycloak.models.KeycloakContext.getClient()" is null
	at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.getShouldUseLightweightToken(AbstractOIDCProtocolMapper.java:86)
	at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.transformAccessToken(AbstractOIDCProtocolMapper.java:91)
	at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:781)
	at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:778)
	at org.keycloak.protocol.oidc.TokenManager$TokenCollector.lambda$accumulator$3(TokenManager.java:941)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.protocol.oidc.TokenManager.transformAccessToken(TokenManager.java:778)
	at org.keycloak.protocol.oidc.TokenManager.createClientAccessToken(TokenManager.java:568)
	at be.looorent.ConfigurableTokenResource.createAccessToken(ConfigurableTokenResource.java:92)
	at be.looorent.ConfigurableTokenResource.createToken(ConfigurableTokenResource.java:73)
	at be.looorent.ConfigurableTokenResource$quarkusrestinvoker$createToken_7d9c2e3d097f63a2055fcf4de0dc064475f263ef.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I'm very new to Keycloak - I'm wondering if I misconfigured something or it is one of 18k Keycloak issues, or something else.

**Comment by looorent** [comment]
Hi @maxnasonov,
Version 25.0.0 of this library had a bug. Since Keycloak 24, certain properties of the session's client (such as `USE_LIGHTWEIGHT_ACCESS_TOKEN_ENABLED`) are required for access token creation, which means the destination session must be linked to a client. This issue has been resolved in Version 25.0.1.
